### ISSUE TITLE
code.google.com is broken

### ISSUE THREAD

**Issue by apognu** [jloup/xml#1]
Hi,

As announced, code.google.com repositories have been removed as of January 2016. The build of this package is broken.

Can we expect a quick migration to either vendored package or new packages for `code.google.com/p/go-charset/charset` and `code.google.com/p/go-charset/data`?

Thank you.

**Comment by jloup** [comment]
Hi,

Thank you for reporting this.

We can use "golang.org/x/net/html/charset" to replace this package.

I made the change on master.
